# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sst/FE/code/incrementalFE/galerkin_tools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sst/FE/code/incrementalFE/galerkin_tools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sst/FE/code/incrementalFE/galerkin_tools/CMakeFiles /home/sst/FE/code/incrementalFE/galerkin_tools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sst/FE/code/incrementalFE/galerkin_tools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named galerkin_tools.debug

# Build rule for target.
galerkin_tools.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 galerkin_tools.debug
.PHONY : galerkin_tools.debug

# fast build rule for target.
galerkin_tools.debug/fast:
	$(MAKE) -f source/CMakeFiles/galerkin_tools.debug.dir/build.make source/CMakeFiles/galerkin_tools.debug.dir/build
.PHONY : galerkin_tools.debug/fast

#=============================================================================
# Target rules for targets named galerkin_tools.release

# Build rule for target.
galerkin_tools.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 galerkin_tools.release
.PHONY : galerkin_tools.release

# fast build rule for target.
galerkin_tools.release/fast:
	$(MAKE) -f source/CMakeFiles/galerkin_tools.release.dir/build.make source/CMakeFiles/galerkin_tools.release.dir/build
.PHONY : galerkin_tools.release/fast

#=============================================================================
# Target rules for targets named triangulation_system_00.debug.diff

# Build rule for target.
triangulation_system_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_00.debug.diff
.PHONY : triangulation_system_00.debug.diff

# fast build rule for target.
triangulation_system_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_00.debug.diff.dir/build.make tests/CMakeFiles/triangulation_system_00.debug.diff.dir/build
.PHONY : triangulation_system_00.debug.diff/fast

#=============================================================================
# Target rules for targets named triangulation_system_00.debug

# Build rule for target.
triangulation_system_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_00.debug
.PHONY : triangulation_system_00.debug

# fast build rule for target.
triangulation_system_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_00.debug.dir/build.make tests/CMakeFiles/triangulation_system_00.debug.dir/build
.PHONY : triangulation_system_00.debug/fast

#=============================================================================
# Target rules for targets named get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff

# Build rule for target.
get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff
.PHONY : get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff

# fast build rule for target.
get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff.dir/build.make tests/CMakeFiles/get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff.dir/build
.PHONY : get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff/fast

#=============================================================================
# Target rules for targets named ldr_decomposition_00.debug

# Build rule for target.
ldr_decomposition_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldr_decomposition_00.debug
.PHONY : ldr_decomposition_00.debug

# fast build rule for target.
ldr_decomposition_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/ldr_decomposition_00.debug.dir/build.make tests/CMakeFiles/ldr_decomposition_00.debug.dir/build
.PHONY : ldr_decomposition_00.debug/fast

#=============================================================================
# Target rules for targets named solver_wrapper_umfpack_00.release.diff

# Build rule for target.
solver_wrapper_umfpack_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver_wrapper_umfpack_00.release.diff
.PHONY : solver_wrapper_umfpack_00.release.diff

# fast build rule for target.
solver_wrapper_umfpack_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/solver_wrapper_umfpack_00.release.diff.dir/build.make tests/CMakeFiles/solver_wrapper_umfpack_00.release.diff.dir/build
.PHONY : solver_wrapper_umfpack_00.release.diff/fast

#=============================================================================
# Target rules for targets named solver_wrapper_umfpack_00.release

# Build rule for target.
solver_wrapper_umfpack_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver_wrapper_umfpack_00.release
.PHONY : solver_wrapper_umfpack_00.release

# fast build rule for target.
solver_wrapper_umfpack_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/solver_wrapper_umfpack_00.release.dir/build.make tests/CMakeFiles/solver_wrapper_umfpack_00.release.dir/build
.PHONY : solver_wrapper_umfpack_00.release/fast

#=============================================================================
# Target rules for targets named solver_wrapper_umfpack_00.debug.diff

# Build rule for target.
solver_wrapper_umfpack_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver_wrapper_umfpack_00.debug.diff
.PHONY : solver_wrapper_umfpack_00.debug.diff

# fast build rule for target.
solver_wrapper_umfpack_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/solver_wrapper_umfpack_00.debug.diff.dir/build.make tests/CMakeFiles/solver_wrapper_umfpack_00.debug.diff.dir/build
.PHONY : solver_wrapper_umfpack_00.debug.diff/fast

#=============================================================================
# Target rules for targets named distance_two_solutions_00.release

# Build rule for target.
distance_two_solutions_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distance_two_solutions_00.release
.PHONY : distance_two_solutions_00.release

# fast build rule for target.
distance_two_solutions_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/distance_two_solutions_00.release.dir/build.make tests/CMakeFiles/distance_two_solutions_00.release.dir/build
.PHONY : distance_two_solutions_00.release/fast

#=============================================================================
# Target rules for targets named distance_two_solutions_00.debug.diff

# Build rule for target.
distance_two_solutions_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distance_two_solutions_00.debug.diff
.PHONY : distance_two_solutions_00.debug.diff

# fast build rule for target.
distance_two_solutions_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/distance_two_solutions_00.debug.diff.dir/build.make tests/CMakeFiles/distance_two_solutions_00.debug.diff.dir/build
.PHONY : distance_two_solutions_00.debug.diff/fast

#=============================================================================
# Target rules for targets named get_nonprimitive_scalar_functional_values_00.debug

# Build rule for target.
get_nonprimitive_scalar_functional_values_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_nonprimitive_scalar_functional_values_00.debug
.PHONY : get_nonprimitive_scalar_functional_values_00.debug

# fast build rule for target.
get_nonprimitive_scalar_functional_values_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/get_nonprimitive_scalar_functional_values_00.debug.dir/build.make tests/CMakeFiles/get_nonprimitive_scalar_functional_values_00.debug.dir/build
.PHONY : get_nonprimitive_scalar_functional_values_00.debug/fast

#=============================================================================
# Target rules for targets named dof_handler_update_interface_00.debug

# Build rule for target.
dof_handler_update_interface_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_handler_update_interface_00.debug
.PHONY : dof_handler_update_interface_00.debug

# fast build rule for target.
dof_handler_update_interface_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/dof_handler_update_interface_00.debug.dir/build.make tests/CMakeFiles/dof_handler_update_interface_00.debug.dir/build
.PHONY : dof_handler_update_interface_00.debug/fast

#=============================================================================
# Target rules for targets named get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff

# Build rule for target.
get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff
.PHONY : get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff

# fast build rule for target.
get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff.dir/build.make tests/CMakeFiles/get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff.dir/build
.PHONY : get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff/fast

#=============================================================================
# Target rules for targets named dof_renumbering_00.release.diff

# Build rule for target.
dof_renumbering_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_renumbering_00.release.diff
.PHONY : dof_renumbering_00.release.diff

# fast build rule for target.
dof_renumbering_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dof_renumbering_00.release.diff.dir/build.make tests/CMakeFiles/dof_renumbering_00.release.diff.dir/build
.PHONY : dof_renumbering_00.release.diff/fast

#=============================================================================
# Target rules for targets named dof_handler_update_interface_00.release.diff

# Build rule for target.
dof_handler_update_interface_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_handler_update_interface_00.release.diff
.PHONY : dof_handler_update_interface_00.release.diff

# fast build rule for target.
dof_handler_update_interface_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dof_handler_update_interface_00.release.diff.dir/build.make tests/CMakeFiles/dof_handler_update_interface_00.release.diff.dir/build
.PHONY : dof_handler_update_interface_00.release.diff/fast

#=============================================================================
# Target rules for targets named dof_renumbering_00.release

# Build rule for target.
dof_renumbering_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_renumbering_00.release
.PHONY : dof_renumbering_00.release

# fast build rule for target.
dof_renumbering_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/dof_renumbering_00.release.dir/build.make tests/CMakeFiles/dof_renumbering_00.release.dir/build
.PHONY : dof_renumbering_00.release/fast

#=============================================================================
# Target rules for targets named dof_renumbering_00.debug

# Build rule for target.
dof_renumbering_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_renumbering_00.debug
.PHONY : dof_renumbering_00.debug

# fast build rule for target.
dof_renumbering_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/dof_renumbering_00.debug.dir/build.make tests/CMakeFiles/dof_renumbering_00.debug.dir/build
.PHONY : dof_renumbering_00.debug/fast

#=============================================================================
# Target rules for targets named ldr_decomposition_00.release.diff

# Build rule for target.
ldr_decomposition_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldr_decomposition_00.release.diff
.PHONY : ldr_decomposition_00.release.diff

# fast build rule for target.
ldr_decomposition_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/ldr_decomposition_00.release.diff.dir/build.make tests/CMakeFiles/ldr_decomposition_00.release.diff.dir/build
.PHONY : ldr_decomposition_00.release.diff/fast

#=============================================================================
# Target rules for targets named dof_renumbering_split_vector_00.debug.diff

# Build rule for target.
dof_renumbering_split_vector_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_renumbering_split_vector_00.debug.diff
.PHONY : dof_renumbering_split_vector_00.debug.diff

# fast build rule for target.
dof_renumbering_split_vector_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dof_renumbering_split_vector_00.debug.diff.dir/build.make tests/CMakeFiles/dof_renumbering_split_vector_00.debug.diff.dir/build
.PHONY : dof_renumbering_split_vector_00.debug.diff/fast

#=============================================================================
# Target rules for targets named dof_handler_system_00.mpirun4.release.diff

# Build rule for target.
dof_handler_system_00.mpirun4.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_handler_system_00.mpirun4.release.diff
.PHONY : dof_handler_system_00.mpirun4.release.diff

# fast build rule for target.
dof_handler_system_00.mpirun4.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dof_handler_system_00.mpirun4.release.diff.dir/build.make tests/CMakeFiles/dof_handler_system_00.mpirun4.release.diff.dir/build
.PHONY : dof_handler_system_00.mpirun4.release.diff/fast

#=============================================================================
# Target rules for targets named dof_handler_system_00.release

# Build rule for target.
dof_handler_system_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_handler_system_00.release
.PHONY : dof_handler_system_00.release

# fast build rule for target.
dof_handler_system_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/dof_handler_system_00.release.dir/build.make tests/CMakeFiles/dof_handler_system_00.release.dir/build
.PHONY : dof_handler_system_00.release/fast

#=============================================================================
# Target rules for targets named ldr_decomposition_00.debug.diff

# Build rule for target.
ldr_decomposition_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldr_decomposition_00.debug.diff
.PHONY : ldr_decomposition_00.debug.diff

# fast build rule for target.
ldr_decomposition_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/ldr_decomposition_00.debug.diff.dir/build.make tests/CMakeFiles/ldr_decomposition_00.debug.diff.dir/build
.PHONY : ldr_decomposition_00.debug.diff/fast

#=============================================================================
# Target rules for targets named derivatives_02.debug.diff

# Build rule for target.
derivatives_02.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_02.debug.diff
.PHONY : derivatives_02.debug.diff

# fast build rule for target.
derivatives_02.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_02.debug.diff.dir/build.make tests/CMakeFiles/derivatives_02.debug.diff.dir/build
.PHONY : derivatives_02.debug.diff/fast

#=============================================================================
# Target rules for targets named triangulation_system_01.debug

# Build rule for target.
triangulation_system_01.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_01.debug
.PHONY : triangulation_system_01.debug

# fast build rule for target.
triangulation_system_01.debug/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_01.debug.dir/build.make tests/CMakeFiles/triangulation_system_01.debug.dir/build
.PHONY : triangulation_system_01.debug/fast

#=============================================================================
# Target rules for targets named dof_renumbering_split_vector_00.release

# Build rule for target.
dof_renumbering_split_vector_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_renumbering_split_vector_00.release
.PHONY : dof_renumbering_split_vector_00.release

# fast build rule for target.
dof_renumbering_split_vector_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/dof_renumbering_split_vector_00.release.dir/build.make tests/CMakeFiles/dof_renumbering_split_vector_00.release.dir/build
.PHONY : dof_renumbering_split_vector_00.release/fast

#=============================================================================
# Target rules for targets named triangulation_system_01.release.diff

# Build rule for target.
triangulation_system_01.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_01.release.diff
.PHONY : triangulation_system_01.release.diff

# fast build rule for target.
triangulation_system_01.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_01.release.diff.dir/build.make tests/CMakeFiles/triangulation_system_01.release.diff.dir/build
.PHONY : triangulation_system_01.release.diff/fast

#=============================================================================
# Target rules for targets named triangulation_system_01.debug.diff

# Build rule for target.
triangulation_system_01.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_01.debug.diff
.PHONY : triangulation_system_01.debug.diff

# fast build rule for target.
triangulation_system_01.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_01.debug.diff.dir/build.make tests/CMakeFiles/triangulation_system_01.debug.diff.dir/build
.PHONY : triangulation_system_01.debug.diff/fast

#=============================================================================
# Target rules for targets named dof_renumbering_00.debug.diff

# Build rule for target.
dof_renumbering_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_renumbering_00.debug.diff
.PHONY : dof_renumbering_00.debug.diff

# fast build rule for target.
dof_renumbering_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dof_renumbering_00.debug.diff.dir/build.make tests/CMakeFiles/dof_renumbering_00.debug.diff.dir/build
.PHONY : dof_renumbering_00.debug.diff/fast

#=============================================================================
# Target rules for targets named assembly_solution_parallel_00.mpirun4.debug.diff

# Build rule for target.
assembly_solution_parallel_00.mpirun4.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_solution_parallel_00.mpirun4.debug.diff
.PHONY : assembly_solution_parallel_00.mpirun4.debug.diff

# fast build rule for target.
assembly_solution_parallel_00.mpirun4.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/assembly_solution_parallel_00.mpirun4.debug.diff.dir/build.make tests/CMakeFiles/assembly_solution_parallel_00.mpirun4.debug.diff.dir/build
.PHONY : assembly_solution_parallel_00.mpirun4.debug.diff/fast

#=============================================================================
# Target rules for targets named assembly_solution_parallel_00.release

# Build rule for target.
assembly_solution_parallel_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_solution_parallel_00.release
.PHONY : assembly_solution_parallel_00.release

# fast build rule for target.
assembly_solution_parallel_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/assembly_solution_parallel_00.release.dir/build.make tests/CMakeFiles/assembly_solution_parallel_00.release.dir/build
.PHONY : assembly_solution_parallel_00.release/fast

#=============================================================================
# Target rules for targets named derivatives_00.release.diff

# Build rule for target.
derivatives_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_00.release.diff
.PHONY : derivatives_00.release.diff

# fast build rule for target.
derivatives_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_00.release.diff.dir/build.make tests/CMakeFiles/derivatives_00.release.diff.dir/build
.PHONY : derivatives_00.release.diff/fast

#=============================================================================
# Target rules for targets named solver_wrapper_petsc_00.mpirun4.release.diff

# Build rule for target.
solver_wrapper_petsc_00.mpirun4.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver_wrapper_petsc_00.mpirun4.release.diff
.PHONY : solver_wrapper_petsc_00.mpirun4.release.diff

# fast build rule for target.
solver_wrapper_petsc_00.mpirun4.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/solver_wrapper_petsc_00.mpirun4.release.diff.dir/build.make tests/CMakeFiles/solver_wrapper_petsc_00.mpirun4.release.diff.dir/build
.PHONY : solver_wrapper_petsc_00.mpirun4.release.diff/fast

#=============================================================================
# Target rules for targets named dof_renumbering_split_vector_00.release.diff

# Build rule for target.
dof_renumbering_split_vector_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_renumbering_split_vector_00.release.diff
.PHONY : dof_renumbering_split_vector_00.release.diff

# fast build rule for target.
dof_renumbering_split_vector_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dof_renumbering_split_vector_00.release.diff.dir/build.make tests/CMakeFiles/dof_renumbering_split_vector_00.release.diff.dir/build
.PHONY : dof_renumbering_split_vector_00.release.diff/fast

#=============================================================================
# Target rules for targets named solver_wrapper_petsc_00.mpirun4.debug.diff

# Build rule for target.
solver_wrapper_petsc_00.mpirun4.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver_wrapper_petsc_00.mpirun4.debug.diff
.PHONY : solver_wrapper_petsc_00.mpirun4.debug.diff

# fast build rule for target.
solver_wrapper_petsc_00.mpirun4.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/solver_wrapper_petsc_00.mpirun4.debug.diff.dir/build.make tests/CMakeFiles/solver_wrapper_petsc_00.mpirun4.debug.diff.dir/build
.PHONY : solver_wrapper_petsc_00.mpirun4.debug.diff/fast

#=============================================================================
# Target rules for targets named assembly_helper_parallel_00.mpirun4.debug.diff

# Build rule for target.
assembly_helper_parallel_00.mpirun4.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_helper_parallel_00.mpirun4.debug.diff
.PHONY : assembly_helper_parallel_00.mpirun4.debug.diff

# fast build rule for target.
assembly_helper_parallel_00.mpirun4.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/assembly_helper_parallel_00.mpirun4.debug.diff.dir/build.make tests/CMakeFiles/assembly_helper_parallel_00.mpirun4.debug.diff.dir/build
.PHONY : assembly_helper_parallel_00.mpirun4.debug.diff/fast

#=============================================================================
# Target rules for targets named triangulation_system_01.release

# Build rule for target.
triangulation_system_01.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_01.release
.PHONY : triangulation_system_01.release

# fast build rule for target.
triangulation_system_01.release/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_01.release.dir/build.make tests/CMakeFiles/triangulation_system_01.release.dir/build
.PHONY : triangulation_system_01.release/fast

#=============================================================================
# Target rules for targets named solver_wrapper_petsc_00.release

# Build rule for target.
solver_wrapper_petsc_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver_wrapper_petsc_00.release
.PHONY : solver_wrapper_petsc_00.release

# fast build rule for target.
solver_wrapper_petsc_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/solver_wrapper_petsc_00.release.dir/build.make tests/CMakeFiles/solver_wrapper_petsc_00.release.dir/build
.PHONY : solver_wrapper_petsc_00.release/fast

#=============================================================================
# Target rules for targets named triangulation_system_02.release

# Build rule for target.
triangulation_system_02.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_02.release
.PHONY : triangulation_system_02.release

# fast build rule for target.
triangulation_system_02.release/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_02.release.dir/build.make tests/CMakeFiles/triangulation_system_02.release.dir/build
.PHONY : triangulation_system_02.release/fast

#=============================================================================
# Target rules for targets named solver_wrapper_petsc_00.debug

# Build rule for target.
solver_wrapper_petsc_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver_wrapper_petsc_00.debug
.PHONY : solver_wrapper_petsc_00.debug

# fast build rule for target.
solver_wrapper_petsc_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/solver_wrapper_petsc_00.debug.dir/build.make tests/CMakeFiles/solver_wrapper_petsc_00.debug.dir/build
.PHONY : solver_wrapper_petsc_00.debug/fast

#=============================================================================
# Target rules for targets named dof_renumbering_split_vector_00.debug

# Build rule for target.
dof_renumbering_split_vector_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_renumbering_split_vector_00.debug
.PHONY : dof_renumbering_split_vector_00.debug

# fast build rule for target.
dof_renumbering_split_vector_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/dof_renumbering_split_vector_00.debug.dir/build.make tests/CMakeFiles/dof_renumbering_split_vector_00.debug.dir/build
.PHONY : dof_renumbering_split_vector_00.debug/fast

#=============================================================================
# Target rules for targets named triangulation_system_02.mpirun4.release.diff

# Build rule for target.
triangulation_system_02.mpirun4.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_02.mpirun4.release.diff
.PHONY : triangulation_system_02.mpirun4.release.diff

# fast build rule for target.
triangulation_system_02.mpirun4.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_02.mpirun4.release.diff.dir/build.make tests/CMakeFiles/triangulation_system_02.mpirun4.release.diff.dir/build
.PHONY : triangulation_system_02.mpirun4.release.diff/fast

#=============================================================================
# Target rules for targets named hanging_node_constraints_00.debug

# Build rule for target.
hanging_node_constraints_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hanging_node_constraints_00.debug
.PHONY : hanging_node_constraints_00.debug

# fast build rule for target.
hanging_node_constraints_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/hanging_node_constraints_00.debug.dir/build.make tests/CMakeFiles/hanging_node_constraints_00.debug.dir/build
.PHONY : hanging_node_constraints_00.debug/fast

#=============================================================================
# Target rules for targets named get_nonprimitive_scalar_functional_values_00.release

# Build rule for target.
get_nonprimitive_scalar_functional_values_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_nonprimitive_scalar_functional_values_00.release
.PHONY : get_nonprimitive_scalar_functional_values_00.release

# fast build rule for target.
get_nonprimitive_scalar_functional_values_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/get_nonprimitive_scalar_functional_values_00.release.dir/build.make tests/CMakeFiles/get_nonprimitive_scalar_functional_values_00.release.dir/build
.PHONY : get_nonprimitive_scalar_functional_values_00.release/fast

#=============================================================================
# Target rules for targets named hanging_node_constraints_00.mpirun4.release.diff

# Build rule for target.
hanging_node_constraints_00.mpirun4.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hanging_node_constraints_00.mpirun4.release.diff
.PHONY : hanging_node_constraints_00.mpirun4.release.diff

# fast build rule for target.
hanging_node_constraints_00.mpirun4.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/hanging_node_constraints_00.mpirun4.release.diff.dir/build.make tests/CMakeFiles/hanging_node_constraints_00.mpirun4.release.diff.dir/build
.PHONY : hanging_node_constraints_00.mpirun4.release.diff/fast

#=============================================================================
# Target rules for targets named dependent_fields_00.release.diff

# Build rule for target.
dependent_fields_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dependent_fields_00.release.diff
.PHONY : dependent_fields_00.release.diff

# fast build rule for target.
dependent_fields_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dependent_fields_00.release.diff.dir/build.make tests/CMakeFiles/dependent_fields_00.release.diff.dir/build
.PHONY : dependent_fields_00.release.diff/fast

#=============================================================================
# Target rules for targets named assembly_helper_parallel_00.debug

# Build rule for target.
assembly_helper_parallel_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_helper_parallel_00.debug
.PHONY : assembly_helper_parallel_00.debug

# fast build rule for target.
assembly_helper_parallel_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/assembly_helper_parallel_00.debug.dir/build.make tests/CMakeFiles/assembly_helper_parallel_00.debug.dir/build
.PHONY : assembly_helper_parallel_00.debug/fast

#=============================================================================
# Target rules for targets named dependent_fields_00.debug

# Build rule for target.
dependent_fields_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dependent_fields_00.debug
.PHONY : dependent_fields_00.debug

# fast build rule for target.
dependent_fields_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/dependent_fields_00.debug.dir/build.make tests/CMakeFiles/dependent_fields_00.debug.dir/build
.PHONY : dependent_fields_00.debug/fast

#=============================================================================
# Target rules for targets named assembly_solution_parallel_00.debug

# Build rule for target.
assembly_solution_parallel_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_solution_parallel_00.debug
.PHONY : assembly_solution_parallel_00.debug

# fast build rule for target.
assembly_solution_parallel_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/assembly_solution_parallel_00.debug.dir/build.make tests/CMakeFiles/assembly_solution_parallel_00.debug.dir/build
.PHONY : assembly_solution_parallel_00.debug/fast

#=============================================================================
# Target rules for targets named compute_map_dofs_00.release

# Build rule for target.
compute_map_dofs_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compute_map_dofs_00.release
.PHONY : compute_map_dofs_00.release

# fast build rule for target.
compute_map_dofs_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/compute_map_dofs_00.release.dir/build.make tests/CMakeFiles/compute_map_dofs_00.release.dir/build
.PHONY : compute_map_dofs_00.release/fast

#=============================================================================
# Target rules for targets named dof_handler_update_interface_00.release

# Build rule for target.
dof_handler_update_interface_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_handler_update_interface_00.release
.PHONY : dof_handler_update_interface_00.release

# fast build rule for target.
dof_handler_update_interface_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/dof_handler_update_interface_00.release.dir/build.make tests/CMakeFiles/dof_handler_update_interface_00.release.dir/build
.PHONY : dof_handler_update_interface_00.release/fast

#=============================================================================
# Target rules for targets named derivatives_01.release.diff

# Build rule for target.
derivatives_01.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_01.release.diff
.PHONY : derivatives_01.release.diff

# fast build rule for target.
derivatives_01.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_01.release.diff.dir/build.make tests/CMakeFiles/derivatives_01.release.diff.dir/build
.PHONY : derivatives_01.release.diff/fast

#=============================================================================
# Target rules for targets named triangulation_system_00.release

# Build rule for target.
triangulation_system_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_00.release
.PHONY : triangulation_system_00.release

# fast build rule for target.
triangulation_system_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_00.release.dir/build.make tests/CMakeFiles/triangulation_system_00.release.dir/build
.PHONY : triangulation_system_00.release/fast

#=============================================================================
# Target rules for targets named distance_two_solutions_00.debug

# Build rule for target.
distance_two_solutions_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distance_two_solutions_00.debug
.PHONY : distance_two_solutions_00.debug

# fast build rule for target.
distance_two_solutions_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/distance_two_solutions_00.debug.dir/build.make tests/CMakeFiles/distance_two_solutions_00.debug.dir/build
.PHONY : distance_two_solutions_00.debug/fast

#=============================================================================
# Target rules for targets named compute_map_dofs_00.mpirun4.debug.diff

# Build rule for target.
compute_map_dofs_00.mpirun4.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compute_map_dofs_00.mpirun4.debug.diff
.PHONY : compute_map_dofs_00.mpirun4.debug.diff

# fast build rule for target.
compute_map_dofs_00.mpirun4.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/compute_map_dofs_00.mpirun4.debug.diff.dir/build.make tests/CMakeFiles/compute_map_dofs_00.mpirun4.debug.diff.dir/build
.PHONY : compute_map_dofs_00.mpirun4.debug.diff/fast

#=============================================================================
# Target rules for targets named compute_map_dofs_00.debug

# Build rule for target.
compute_map_dofs_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compute_map_dofs_00.debug
.PHONY : compute_map_dofs_00.debug

# fast build rule for target.
compute_map_dofs_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/compute_map_dofs_00.debug.dir/build.make tests/CMakeFiles/compute_map_dofs_00.debug.dir/build
.PHONY : compute_map_dofs_00.debug/fast

#=============================================================================
# Target rules for targets named assembly_solution_parallel_00.mpirun4.release.diff

# Build rule for target.
assembly_solution_parallel_00.mpirun4.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_solution_parallel_00.mpirun4.release.diff
.PHONY : assembly_solution_parallel_00.mpirun4.release.diff

# fast build rule for target.
assembly_solution_parallel_00.mpirun4.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/assembly_solution_parallel_00.mpirun4.release.diff.dir/build.make tests/CMakeFiles/assembly_solution_parallel_00.mpirun4.release.diff.dir/build
.PHONY : assembly_solution_parallel_00.mpirun4.release.diff/fast

#=============================================================================
# Target rules for targets named hanging_node_constraints_00.release

# Build rule for target.
hanging_node_constraints_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hanging_node_constraints_00.release
.PHONY : hanging_node_constraints_00.release

# fast build rule for target.
hanging_node_constraints_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/hanging_node_constraints_00.release.dir/build.make tests/CMakeFiles/hanging_node_constraints_00.release.dir/build
.PHONY : hanging_node_constraints_00.release/fast

#=============================================================================
# Target rules for targets named hanging_node_constraints_00.mpirun4.debug.diff

# Build rule for target.
hanging_node_constraints_00.mpirun4.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hanging_node_constraints_00.mpirun4.debug.diff
.PHONY : hanging_node_constraints_00.mpirun4.debug.diff

# fast build rule for target.
hanging_node_constraints_00.mpirun4.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/hanging_node_constraints_00.mpirun4.debug.diff.dir/build.make tests/CMakeFiles/hanging_node_constraints_00.mpirun4.debug.diff.dir/build
.PHONY : hanging_node_constraints_00.mpirun4.debug.diff/fast

#=============================================================================
# Target rules for targets named derivatives_02.release

# Build rule for target.
derivatives_02.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_02.release
.PHONY : derivatives_02.release

# fast build rule for target.
derivatives_02.release/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_02.release.dir/build.make tests/CMakeFiles/derivatives_02.release.dir/build
.PHONY : derivatives_02.release/fast

#=============================================================================
# Target rules for targets named derivatives_02.release.diff

# Build rule for target.
derivatives_02.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_02.release.diff
.PHONY : derivatives_02.release.diff

# fast build rule for target.
derivatives_02.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_02.release.diff.dir/build.make tests/CMakeFiles/derivatives_02.release.diff.dir/build
.PHONY : derivatives_02.release.diff/fast

#=============================================================================
# Target rules for targets named dependent_fields_00.debug.diff

# Build rule for target.
dependent_fields_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dependent_fields_00.debug.diff
.PHONY : dependent_fields_00.debug.diff

# fast build rule for target.
dependent_fields_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dependent_fields_00.debug.diff.dir/build.make tests/CMakeFiles/dependent_fields_00.debug.diff.dir/build
.PHONY : dependent_fields_00.debug.diff/fast

#=============================================================================
# Target rules for targets named dependent_fields_00.release

# Build rule for target.
dependent_fields_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dependent_fields_00.release
.PHONY : dependent_fields_00.release

# fast build rule for target.
dependent_fields_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/dependent_fields_00.release.dir/build.make tests/CMakeFiles/dependent_fields_00.release.dir/build
.PHONY : dependent_fields_00.release/fast

#=============================================================================
# Target rules for targets named derivatives_00.debug.diff

# Build rule for target.
derivatives_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_00.debug.diff
.PHONY : derivatives_00.debug.diff

# fast build rule for target.
derivatives_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_00.debug.diff.dir/build.make tests/CMakeFiles/derivatives_00.debug.diff.dir/build
.PHONY : derivatives_00.debug.diff/fast

#=============================================================================
# Target rules for targets named derivatives_00.debug

# Build rule for target.
derivatives_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_00.debug
.PHONY : derivatives_00.debug

# fast build rule for target.
derivatives_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_00.debug.dir/build.make tests/CMakeFiles/derivatives_00.debug.dir/build
.PHONY : derivatives_00.debug/fast

#=============================================================================
# Target rules for targets named derivatives_01.release

# Build rule for target.
derivatives_01.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_01.release
.PHONY : derivatives_01.release

# fast build rule for target.
derivatives_01.release/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_01.release.dir/build.make tests/CMakeFiles/derivatives_01.release.dir/build
.PHONY : derivatives_01.release/fast

#=============================================================================
# Target rules for targets named solver_wrapper_umfpack_00.debug

# Build rule for target.
solver_wrapper_umfpack_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver_wrapper_umfpack_00.debug
.PHONY : solver_wrapper_umfpack_00.debug

# fast build rule for target.
solver_wrapper_umfpack_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/solver_wrapper_umfpack_00.debug.dir/build.make tests/CMakeFiles/solver_wrapper_umfpack_00.debug.dir/build
.PHONY : solver_wrapper_umfpack_00.debug/fast

#=============================================================================
# Target rules for targets named derivatives_00.release

# Build rule for target.
derivatives_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_00.release
.PHONY : derivatives_00.release

# fast build rule for target.
derivatives_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_00.release.dir/build.make tests/CMakeFiles/derivatives_00.release.dir/build
.PHONY : derivatives_00.release/fast

#=============================================================================
# Target rules for targets named derivatives_02.debug

# Build rule for target.
derivatives_02.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_02.debug
.PHONY : derivatives_02.debug

# fast build rule for target.
derivatives_02.debug/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_02.debug.dir/build.make tests/CMakeFiles/derivatives_02.debug.dir/build
.PHONY : derivatives_02.debug/fast

#=============================================================================
# Target rules for targets named triangulation_system_02.debug

# Build rule for target.
triangulation_system_02.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_02.debug
.PHONY : triangulation_system_02.debug

# fast build rule for target.
triangulation_system_02.debug/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_02.debug.dir/build.make tests/CMakeFiles/triangulation_system_02.debug.dir/build
.PHONY : triangulation_system_02.debug/fast

#=============================================================================
# Target rules for targets named derivatives_01.debug.diff

# Build rule for target.
derivatives_01.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_01.debug.diff
.PHONY : derivatives_01.debug.diff

# fast build rule for target.
derivatives_01.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_01.debug.diff.dir/build.make tests/CMakeFiles/derivatives_01.debug.diff.dir/build
.PHONY : derivatives_01.debug.diff/fast

#=============================================================================
# Target rules for targets named assembly_helper_parallel_00.release

# Build rule for target.
assembly_helper_parallel_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_helper_parallel_00.release
.PHONY : assembly_helper_parallel_00.release

# fast build rule for target.
assembly_helper_parallel_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/assembly_helper_parallel_00.release.dir/build.make tests/CMakeFiles/assembly_helper_parallel_00.release.dir/build
.PHONY : assembly_helper_parallel_00.release/fast

#=============================================================================
# Target rules for targets named assembly_helper_parallel_00.mpirun4.release.diff

# Build rule for target.
assembly_helper_parallel_00.mpirun4.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_helper_parallel_00.mpirun4.release.diff
.PHONY : assembly_helper_parallel_00.mpirun4.release.diff

# fast build rule for target.
assembly_helper_parallel_00.mpirun4.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/assembly_helper_parallel_00.mpirun4.release.diff.dir/build.make tests/CMakeFiles/assembly_helper_parallel_00.mpirun4.release.diff.dir/build
.PHONY : assembly_helper_parallel_00.mpirun4.release.diff/fast

#=============================================================================
# Target rules for targets named triangulation_system_00.release.diff

# Build rule for target.
triangulation_system_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_00.release.diff
.PHONY : triangulation_system_00.release.diff

# fast build rule for target.
triangulation_system_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_00.release.diff.dir/build.make tests/CMakeFiles/triangulation_system_00.release.diff.dir/build
.PHONY : triangulation_system_00.release.diff/fast

#=============================================================================
# Target rules for targets named derivatives_01.debug

# Build rule for target.
derivatives_01.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivatives_01.debug
.PHONY : derivatives_01.debug

# fast build rule for target.
derivatives_01.debug/fast:
	$(MAKE) -f tests/CMakeFiles/derivatives_01.debug.dir/build.make tests/CMakeFiles/derivatives_01.debug.dir/build
.PHONY : derivatives_01.debug/fast

#=============================================================================
# Target rules for targets named ldr_decomposition_00.release

# Build rule for target.
ldr_decomposition_00.release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldr_decomposition_00.release
.PHONY : ldr_decomposition_00.release

# fast build rule for target.
ldr_decomposition_00.release/fast:
	$(MAKE) -f tests/CMakeFiles/ldr_decomposition_00.release.dir/build.make tests/CMakeFiles/ldr_decomposition_00.release.dir/build
.PHONY : ldr_decomposition_00.release/fast

#=============================================================================
# Target rules for targets named dof_handler_update_interface_00.debug.diff

# Build rule for target.
dof_handler_update_interface_00.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_handler_update_interface_00.debug.diff
.PHONY : dof_handler_update_interface_00.debug.diff

# fast build rule for target.
dof_handler_update_interface_00.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dof_handler_update_interface_00.debug.diff.dir/build.make tests/CMakeFiles/dof_handler_update_interface_00.debug.diff.dir/build
.PHONY : dof_handler_update_interface_00.debug.diff/fast

#=============================================================================
# Target rules for targets named dof_handler_system_00.debug

# Build rule for target.
dof_handler_system_00.debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_handler_system_00.debug
.PHONY : dof_handler_system_00.debug

# fast build rule for target.
dof_handler_system_00.debug/fast:
	$(MAKE) -f tests/CMakeFiles/dof_handler_system_00.debug.dir/build.make tests/CMakeFiles/dof_handler_system_00.debug.dir/build
.PHONY : dof_handler_system_00.debug/fast

#=============================================================================
# Target rules for targets named distance_two_solutions_00.release.diff

# Build rule for target.
distance_two_solutions_00.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distance_two_solutions_00.release.diff
.PHONY : distance_two_solutions_00.release.diff

# fast build rule for target.
distance_two_solutions_00.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/distance_two_solutions_00.release.diff.dir/build.make tests/CMakeFiles/distance_two_solutions_00.release.diff.dir/build
.PHONY : distance_two_solutions_00.release.diff/fast

#=============================================================================
# Target rules for targets named triangulation_system_02.mpirun4.debug.diff

# Build rule for target.
triangulation_system_02.mpirun4.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulation_system_02.mpirun4.debug.diff
.PHONY : triangulation_system_02.mpirun4.debug.diff

# fast build rule for target.
triangulation_system_02.mpirun4.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/triangulation_system_02.mpirun4.debug.diff.dir/build.make tests/CMakeFiles/triangulation_system_02.mpirun4.debug.diff.dir/build
.PHONY : triangulation_system_02.mpirun4.debug.diff/fast

#=============================================================================
# Target rules for targets named compute_map_dofs_00.mpirun4.release.diff

# Build rule for target.
compute_map_dofs_00.mpirun4.release.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compute_map_dofs_00.mpirun4.release.diff
.PHONY : compute_map_dofs_00.mpirun4.release.diff

# fast build rule for target.
compute_map_dofs_00.mpirun4.release.diff/fast:
	$(MAKE) -f tests/CMakeFiles/compute_map_dofs_00.mpirun4.release.diff.dir/build.make tests/CMakeFiles/compute_map_dofs_00.mpirun4.release.diff.dir/build
.PHONY : compute_map_dofs_00.mpirun4.release.diff/fast

#=============================================================================
# Target rules for targets named dof_handler_system_00.mpirun4.debug.diff

# Build rule for target.
dof_handler_system_00.mpirun4.debug.diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dof_handler_system_00.mpirun4.debug.diff
.PHONY : dof_handler_system_00.mpirun4.debug.diff

# fast build rule for target.
dof_handler_system_00.mpirun4.debug.diff/fast:
	$(MAKE) -f tests/CMakeFiles/dof_handler_system_00.mpirun4.debug.diff.dir/build.make tests/CMakeFiles/dof_handler_system_00.mpirun4.debug.diff.dir/build
.PHONY : dof_handler_system_00.mpirun4.debug.diff/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... galerkin_tools.debug"
	@echo "... galerkin_tools.release"
	@echo "... triangulation_system_00.debug.diff"
	@echo "... triangulation_system_00.debug"
	@echo "... get_nonprimitive_scalar_functional_values_00.mpirun4.release.diff"
	@echo "... ldr_decomposition_00.debug"
	@echo "... solver_wrapper_umfpack_00.release.diff"
	@echo "... solver_wrapper_umfpack_00.release"
	@echo "... solver_wrapper_umfpack_00.debug.diff"
	@echo "... distance_two_solutions_00.release"
	@echo "... distance_two_solutions_00.debug.diff"
	@echo "... get_nonprimitive_scalar_functional_values_00.debug"
	@echo "... dof_handler_update_interface_00.debug"
	@echo "... get_nonprimitive_scalar_functional_values_00.mpirun4.debug.diff"
	@echo "... dof_renumbering_00.release.diff"
	@echo "... dof_handler_update_interface_00.release.diff"
	@echo "... dof_renumbering_00.release"
	@echo "... dof_renumbering_00.debug"
	@echo "... ldr_decomposition_00.release.diff"
	@echo "... dof_renumbering_split_vector_00.debug.diff"
	@echo "... dof_handler_system_00.mpirun4.release.diff"
	@echo "... dof_handler_system_00.release"
	@echo "... ldr_decomposition_00.debug.diff"
	@echo "... derivatives_02.debug.diff"
	@echo "... triangulation_system_01.debug"
	@echo "... dof_renumbering_split_vector_00.release"
	@echo "... triangulation_system_01.release.diff"
	@echo "... triangulation_system_01.debug.diff"
	@echo "... dof_renumbering_00.debug.diff"
	@echo "... assembly_solution_parallel_00.mpirun4.debug.diff"
	@echo "... assembly_solution_parallel_00.release"
	@echo "... derivatives_00.release.diff"
	@echo "... solver_wrapper_petsc_00.mpirun4.release.diff"
	@echo "... dof_renumbering_split_vector_00.release.diff"
	@echo "... solver_wrapper_petsc_00.mpirun4.debug.diff"
	@echo "... assembly_helper_parallel_00.mpirun4.debug.diff"
	@echo "... triangulation_system_01.release"
	@echo "... solver_wrapper_petsc_00.release"
	@echo "... triangulation_system_02.release"
	@echo "... solver_wrapper_petsc_00.debug"
	@echo "... dof_renumbering_split_vector_00.debug"
	@echo "... triangulation_system_02.mpirun4.release.diff"
	@echo "... hanging_node_constraints_00.debug"
	@echo "... get_nonprimitive_scalar_functional_values_00.release"
	@echo "... hanging_node_constraints_00.mpirun4.release.diff"
	@echo "... dependent_fields_00.release.diff"
	@echo "... assembly_helper_parallel_00.debug"
	@echo "... dependent_fields_00.debug"
	@echo "... assembly_solution_parallel_00.debug"
	@echo "... compute_map_dofs_00.release"
	@echo "... dof_handler_update_interface_00.release"
	@echo "... derivatives_01.release.diff"
	@echo "... triangulation_system_00.release"
	@echo "... distance_two_solutions_00.debug"
	@echo "... compute_map_dofs_00.mpirun4.debug.diff"
	@echo "... compute_map_dofs_00.debug"
	@echo "... assembly_solution_parallel_00.mpirun4.release.diff"
	@echo "... hanging_node_constraints_00.release"
	@echo "... hanging_node_constraints_00.mpirun4.debug.diff"
	@echo "... derivatives_02.release"
	@echo "... derivatives_02.release.diff"
	@echo "... dependent_fields_00.debug.diff"
	@echo "... dependent_fields_00.release"
	@echo "... derivatives_00.debug.diff"
	@echo "... derivatives_00.debug"
	@echo "... derivatives_01.release"
	@echo "... solver_wrapper_umfpack_00.debug"
	@echo "... derivatives_00.release"
	@echo "... derivatives_02.debug"
	@echo "... triangulation_system_02.debug"
	@echo "... derivatives_01.debug.diff"
	@echo "... assembly_helper_parallel_00.release"
	@echo "... assembly_helper_parallel_00.mpirun4.release.diff"
	@echo "... triangulation_system_00.release.diff"
	@echo "... derivatives_01.debug"
	@echo "... ldr_decomposition_00.release"
	@echo "... dof_handler_update_interface_00.debug.diff"
	@echo "... dof_handler_system_00.debug"
	@echo "... distance_two_solutions_00.release.diff"
	@echo "... triangulation_system_02.mpirun4.debug.diff"
	@echo "... compute_map_dofs_00.mpirun4.release.diff"
	@echo "... dof_handler_system_00.mpirun4.debug.diff"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

